---
- name: Example of use of plugins and modules from a collection
  hosts: lc_example
  gather_facts: false
  pre_tasks:
    - name: Reporting group_vars value from the collection
      debug:
        var: lc_example_of_group_var  
  tasks:
    - name: Lookup plugin
      debug:
        msg: "{{ lookup('lidofinance.core.hello_world') }}"
    - name: Callig a module
      lidofinance.core.hello_world:
      register: lc_hello_message
    - name: Reporting
      debug:
        var: lc_hello_message.message
